ess-dmsc/nicos

nicos_ess/loki/gui/sampleconf.py
This PR proposes minor code revisions in `sampleconf.py` including:
- The global variable `SAMPLE_KEYS` is now wrapped in a function which returns a tuple rather than a list to ensure arbitrary values cannot be assigned to it, by mistake.
- Some variables are renamed 
- The function `on_actionGenerate_triggered` is refactored.
=> Minor code revisions in Loki GUI

nicos_ess/loki/guiconfig.py
=> Remove tab container as only one tab

nicos_ess/loki/gui/sampleconf.py
Simple change, similar to the others done this week
=> ECDC-2192: samples view should "grey-out" when in view-only mode

nicos_ess/loki/gui/measdialogs.py, nicos_ess/loki/gui/sampleconf.py, nicos_ess/loki/gui/ui_files/sampleconf_one.ui, nicos_ess/loki/gui/ui_files/sampleconf_summary.ui
This PR removes `measurement time factor` from sample configuration.
=> Remove measurement time factor

nicos_ess/guiconfig.qss, nicos_ess/loki/guiconfig.qss
This fixes the down-arrow style issue in new history window of the UI.
=> Fix down-arrow style

nicos_ess/loki/gui/sampleconf.py
This PR fixes a small bug rises due to usage of wrong object.
=> LoKI: Fix a small bug related to Thickness 

nicos_ess/loki/setups/special/daemon.py
This should solve the strange issue with NICOS and EPICS we saw on Kenan's machine.
This fix should go into Gerrit
=> Need to import EPICS in the daemon

nicos_ess/loki/gui/sampleconf.py
Fixes the bug reported [here](https://github.com/ess-dmsc/nicos/pull/48#issuecomment-768967296).
=> Set aperture only if value changes

nicos_ess/loki/gui/sampleconf.py
This PR may address the issue mentioned [here](https://github.com/ess-dmsc/nicos/pull/53#issuecomment-775134472)
=> ECDC-2318: Apply Button becomes active when typing in aperture box

nicos_ess/loki/gui/sampleconf.py, nicos_ess/loki/gui/ui_files/sampleconf_summary.ui
This PR address the issue mentioned [here](https://github.com/ess-dmsc/nicos/pull/58#discussion_r578200484)
=> ECDC-2327: Refactor list item clicked method

nicos_ess/loki/guiconfig.qss
Merging loki gui specific qss file which were not merged in Gerrit.
=> Ecdc 2264 loki qss file update

nicos_ess/ymir/setups/mini_chopper.py
It's another good test of the code and it lets us see more clearly how the value fluctuates.
=> Change the fast changing chopper PVs to use the PV monitors

nicos_ess/devices/epics/pva/epics_devices.py
Nothing major, just needs a second set of eyes to check for obvious copy and paste mistakes ;)
=> Renamed some fields for consistency and removed some duplication

nicos_ess/loki/gui/loki_scriptbuilder.py, nicos_ess/loki/gui/ui_files/loki_scriptbuilder.ui
This is just GUI manipulation stuff.
=> ECDC-2355: add copy, paste and insert functionality

nicos_ess/loki/gui/setup_exp.py, nicos_ess/loki/gui/ui_files/setup_exp.ui
Changes in LoKI ONLY for proposal setup warning label.
=> Adding warning label for proposal setup panel for LoKI only

nicos_ess/gui/utilities/load_save_tables.py
=> Use NICOS "standard" docstring style

nicos_ess/loki/gui/setup_exp.py
Changes in LOKI already approved in closed PR. Removal of 2 setText calls. Merging to github main branch directly.
=> Removing setText calls in on_client connected

nicos_ess/ymir/commands/nexus_config.json
=> Added PLC senv test source.

nicos_ess/loki/gui/connection_listener.py, nicos_ess/loki/gui/experiment_conf.py, nicos_ess/loki/gui/loki_panel.py, nicos_ess/loki/gui/loki_scriptbuilder.py, nicos_ess/loki/gui/sampleconf.py, nicos_ess/loki/gui/scriptbuilder.py, nicos_ess/loki/gui/setup_exp.py
This PR introduces a base class for LoKI panel. This introduction removes the code repetitions in four files. The implemented class can be extended in the future to hold relevant functionalities.
=> LoKI: Implement base class for panel

nicos_ess/loki/gui/scriptbuilder.py
This PR cleans `scriptbuilder.py` from some repetitions.
=> LoKI: Remove code repetitions in script builder 

bin/nicos-forwarder
I think these are the most "chatty" logs.
Reducing them to debug should mean they don't appear under normal settings.
Needs to be tried at YMIR first.
=> Reduce logging level.

nicos_ess/loki/gui/loki_scriptbuilder_model.py
Delete all the rows -> click on table throws error because it cannot access the column.
=> Bugfix with no rows

nicos_ess/loki/gui/loki_scriptbuilder.py, nicos_ess/loki/gui/script_generator.py
Create factory class for script generation
=> ECDC-2486:  loki script factory

nicos_ess/loki/gui/loki_scriptbuilder.py
This PR will not allow multi selection copy. Multi-selection paste will just throw a warning.
=> Allow only contiguous selection during copy-paste

nicos_ess/loki/gui/loki_scriptbuilder_model.py
Minor change to avoid in-place modification of data read from file.
=> Avoid inplace modification of incoming data in setter

nicos_ess/loki/gui/loki_scriptbuilder.py, nicos_ess/loki/gui/script_generator.py, nicos_ess/loki/gui/ui_files/loki_scriptbuilder.ui
Use "do sans/trans" times for different transorders. Try this if it makes sense.
=> ECDC-2492:  Use "do sans/trans" times

nicos_ess/loki/gui/loki_scriptbuilder.py
=> Revert "Handle unnecessary empty cells copy-paste"

nicos_ess/loki/gui/loki_scriptbuilder.py
This PR adds the material icons for the right click actions in prototype table.
=> LoKI: Add proper icons to right click context menu

nicos_ess/loki/gui/setup_exp.py
Just updated the authors and remove the redundant "future" imports
=> Loki exp panel tidy up

Jenkinsfile
=> Updating Jenkinsfile with pip install requirements-opt

nicos_ess/loki/gui/loki_scriptbuilder_model.py
Makes it a bit harder to break something ;)
=> LokiScript: Return a copy of the table data

nicos_ess/loki/gui/script_generator.py
It only does set_sample etc. once when doing `trans then sans` and `sans then trans`
Also, refactored the code somewhat.
=> ECDC-2493 set sample only once if doing consectutive runs on same sample

nicos_ess/devices/epics/pva/monitor_motor.py
As I will be out and about today, we won't have a chance to talk directly so I have put some ideas in this PR.
I've not tested the changes other than NICOS can load the device.
Don't merge this ;)
=> Motor msgtxt suggestions

test/nicos_ess/test_utilities/test_validator.py
Just a couple of simple unit tests for the new validator class.
=> Ecdc 2534 add unit tests for validator

nicos_ess/gui/panels/setup_panel.py, nicos_ess/gui/panels/ui_files/setup_exp.ui
Adds a button to discard unapplied changes to the proposal information
=> ECDC-2517: Add discard changes button for proposal page

nicos_ess/devices/experiment.py
This extracts and returns the samples as part of the proposal query.
NICOS doesn't do anything with them yet - that will be in another PR
=> ECDC-2267: return the samples

nicos_ess/ymir/commands/nexus_config.json
=> Added NICOS devices.

nicos_ess/dream/nicos.conf, nicos_ess/dream/setups/special/collector.py
=> ECDC-2557: Add collector device in DREAM instrument

nicos_ess/gui/panels/setup_panel.py
To test, temporarily add `result = [result[0], deepcopy(result[0])]` before line 388 (`if result:`)
=> ECDC-2559: Added missing method for choosing from multiple proposals

tmux_scripts/start_nicos_ymir.sh
Updates according to ticket:
https://jira.esss.lu.se/browse/ECDC-2563
=> updating start_nicos_ymir.sh

nicos_ess/devices/experiment.py
Reverts ess-dmsc/nicos#155
Found a bug, so reverting for now
=> Revert "ECDC:2560 Finish Experiment should clear the samples."

nicos_ess/loki/guiconfig.py
Changes the config so that ui runs properly.
=> Change config

nicos_ess/devices/epics/motor.py
The base implementation is sufficient.
=> Remove unnecessary overridden method from derived class
