nicos/clients/gui/panels/editor.py

This PR fixes the error message that pops up when one presses the `Run` button in `Script Editor` if there is no active connection to the server.

Fix error message when pressed Run while disconnected

---

nicos_ess/loki/gui/sampleconf.py

This PR fixes the `NoneType` error when no device is selected. The error occurs due to the initialisation `dlg.widget = None` at line `165`. When no device is selected, the call to `.getValue()` method at line `181` fails as `NoneType` has no such attribute.

Fix nonetype error when no device is selected

---

nicos_ess/loki/gui/sampleconf.py
nicos_ess/loki/gui/sampleconf.ui
nicos_ess/loki/gui/sampleconf_one.ui

This PR refactors the corresponding codes for `save` and `apply` buttons in the Loki GUI. With these changes `save` button only does save the script, while `apply` button sends the script to the `daemon` without saving it.

Refactor save&apply buttons in Loki GUI

---

nicos_ess/loki/gui/sampleconf.py
nicos_ess/loki/gui/sampleconf.ui

Renamed "save" and "apply" buttons as discussed. I think these names are more descriptive, we can see what the instrument scientist thinks next time we meet.
The "dirty" functionality was not behaving correctly so that has been changed.
Also there was a bug when the retrieve button was clicked twice - I fixed that. There are similar bugs for the other buttons, but I will fix those in a separate PR.

Renamed sample related buttons

---

nicos_ess/loki/gui/sampleconf.py
nicos_ess/loki/gui/sampleconf.ui
nicos_ess/loki/guiconfig.py

I've gone through the code for the buttons and tried to find ways to break it, and if I managed to then I fixed it.
I added some place-holder sample changers so that for demos we can use the "generate" buttons - I also needed them for testing the code. At some point it would be good to tie it to the simulated LoKI sample changers, I'll create a ticket for that.

Fix broken sample buttons

---

nicos_ess/loki/gui/sampleconf.py

The buttons should be disabled/enabled based on the connection state

Disable sample-related buttons when disconnected

---

nicos_ess/loki/gui/sampleconf.py
nicos_ess/loki/gui/sampleconf.ui
nicos_ess/loki/gui/sampleconf_summary.ui

After some investigation, I worked out that we could change the buttons via Qt Designer to have a strong-focus; this means that when we click on the buttons the buttons take focus. This should mean that the editingFinished behviour for the text boxes should work properly now.
I also added a place-holder method for when the button for reading the aperture settings is clicked.

Move to using editing finished

---

nicos_ess/loki/gui/cmdlets.py
nicos_ess/loki/gui/instrconfig.py
nicos_ess/loki/gui/protocol.py
nicos_ess/loki/gui/sampleconf.py
nicos_ess/loki/gui/setup_panel.py

The GUI code still had some references to the compatibility layer for Python 2, this removes that.
Once this has been done we can re-sync this against the latest version of master.

Remove Python 2 compatibility

---

nicos_ess/loki/gui/ui_files/detsets.ui
nicos_ess/loki/gui/ui_files/devices.ui
nicos_ess/loki/gui/ui_files/devices_one.ui
nicos_ess/loki/gui/ui_files/protocol.ui
nicos_ess/loki/gui/ui_files/samples.ui
nicos_ess/loki/gui/ui_files/table.ui

Needed to add an extra `../` so Qt Designer can find the resource file for icons etc.
I don't think this matters for the GUI itself, but Qt Designer complained so I fixed it.

Moving the UI files meant the path to the resources file was wrong

---

nicos_ess/loki/gui/setup_exp.py
nicos_ess/loki/gui/ui_files/setup_exp.ui

Changes to the setup_exp:
* disable controls when view-only and disconnected
* clear the text contents when disconnected
* Removed send data textfield as that is not needed

Experiment tab: disable and clear controls when disconnected

---

nicos_ess/gui/mainwindow.py
resources/material/icons/emergency_stop.svg

This PR proposes a material design for emergency stop button.
Note: The new icon does not require a license to be added as it is already in nicos/license with material.io Apache license. So we are good to go.

Change emergency button icon

---

nicos_ess/loki/gui/sampleconf.py

This PR adds a warning to the sample config UI if the `thickness` is equal to zero. The next check already handles if it is `None`.

LoKI: Warn if thickness is zero

---

nicos_ess/loki/devices/sample.py
nicos_ess/loki/setups/system.py

Doesn't do anything interesting at the moment, but we will need it for ECDC-2208 and other LoKI tickets in the future.

Added LoKI specific sample class

---

bin/nicos-forwarder.py

This uses a new service to get the values from NICOS and send them to Kafka.
I think it is cleaner than doing it in NICOS itself as it allows the NICOS cache just to run as normal.

ECDC-2223: forward NICOS values to Kafka

---

nicos_ess/loki/gui/sampleconf.py

This PR makes sure that `Apply Changes` button is enabled if and only if there are changes in the sample configurations.

LoKI: Enable apply button if there are changes

---

bin/nicos-forwarder
tmux_scripts/start_nicos_ymir.sh

This should be running at all times for YMIR from now on.

Add starting the nicos-forwarder as part of the YMIR tmux-script

---

nicos_ess/loki/gui/sampleconf.py

When sample configuration contains invalid inputs (like blank fields), pressing the Apply button will show warning and sample info will not be transferred to the daemon.

ECDC-2320: Warn if sample input fields have invalid inputs

---

nicos_ess/loki/gui/setup_exp.py
nicos_ess/loki/gui/ui_files/setup_exp.ui

This replaces `dialogButtonBox` with `QPushButton` in the Experiment panel of LoKI gui.

ECDC-2335: Replace buttonbox with PushButton in LoKi exp setup

---

nicos_ess/devices/epics/pva/epics_devices.py

It shouldn't be changed by outsiders, so let's make it private to indicate that
Just renaming, so no changes to functionality.

p4p epics devices: make PV parameters field private

---

nicos_ess/loki/gui/scriptbuilder.py

This PR disables command builders in Script Editor tab in the UI if the client is disconnected or UI is in view only mode.

LoKI Script Editor: Disable command builders if disconnected or view only  

---

nicos_ess/loki/guiconfig.py

This PR moves the command line to the bottom in the instrument interaction tab of the UI in accordance with the instrument scientists.

LoKI: Move Command Line to Bottom

---

nicos_ess/loki/gui/sampleconf.py
nicos_ess/loki/gui/ui_files/sampleconf_one.ui
nicos_ess/loki/gui/ui_files/sampleconf_summary.ui

This PR removes the instrument configuration concerning aperture and detector offset from the Samples tab of the LoKI GUI. These setting will be moved to a new tab in accordance of the wishes of the instrument scientists.

LoKI: Remove Instrument Set-Up (Aperture and Offset) from Samples Tab

---

nicos_ess/loki/gui/experiment_conf.py
nicos_ess/loki/gui/ui_files/exp_config.ui
nicos_ess/loki/guiconfig.py

This PR introduces a new tab in the LoKI GUI, called `Experiment Configuration`. This new tab currently holds `Aperture` and `Detector Offset` values. The corresponding code base has been initialised however the tab has no functionality at this time.
Upon a discussion with the instrument scientists, the requested functionalities shall be added.

LoKI: Create a new Tab for Experiment Configuration

---

nicos_ess/loki/gui/sampleconf.py

This PR fixes a small bug in sample configuration (basically sample configuration panel should be disabled on the frame, one must click edit to edit). The bug formed because I mistakenly deleted that line during refactoring the experiment configuration to a new tab.

Fix a small bug formed during refactoring experiment config to a new tab

---

nicos_ess/loki/gui/loki_scriptbuilder.py
nicos_ess/loki/gui/loki_scriptbuilder_model.py

When no rows exist in a table insert row above and below creates an empty row.

Create row above and button work when no rows exist

---

nicos_ess/loki/gui/ui_files/loki_scriptbuilder.ui

Stops the setting panels on the left collapsing

Make loki script settings resize correctly

---

nicos_ess/loki/gui/loki_scriptbuilder.py
nicos_ess/loki/gui/loki_scriptbuilder_model.py
nicos_ess/loki/gui/script_generator.py

This PR fix some PEP issues, adds headers and make some other corrections to the codes that handle script generation and table manipulation for LoKI.
On the side note:
@mattclarke and @ebadkamil 
If one chooses `SIMULTANEOUS` as trans order in settings in `Prototype` tab, Python throws an error concerning positional arguments (required 2 but given 3). This only happens for `SIMULTANEOUS`.

LoKI: Fix things in script builder codes

---

nicos_ess/loki/gui/script_generator.py

This PR replaces `if-elif-else` chain in `ScriptGenerator` class method with a dictionary switch. The new implementation is tested as follows:
- A script is generated for all Trans options and saved along with the table that generates them.
- New method is implemented.
- Saved table loaded and each script is generated with the new implementation and saved.
- Generated scripts are then compared with Unix's built in `diff`. Scripts are identical.

LoKI: Replace if-elif-else with dict switch in script generator

---

nicos_ess/loki/gui/sampleconf.py

When one clicks the `Empty` under `Create New` in `Select a sample list` in `Samples` tab, it is required to click `New` at the bottom-left as a second step. This PR removes this unnecessary step by wiring these two action up without effecting the original behaviour of the `Empty`.

LoKI: Wire up action 'empty' with 'new' to reduce two step action to one

---

nicos_ess/loki/gui/loki_scriptbuilder.py
nicos_ess/loki/gui/loki_scriptbuilder_model.py

This PR  fixes the bug (mentioned below) when pasting data in table with hidden columns. 
`Bug: Pasting a b c d e f g => f skipped due to hidden temperature column.`

Bugfix: pasting data in table with hidden columns

---

nicos_ess/loki/gui/loki_scriptbuilder_model.py

If one double-clicks on a cell with a value in it then the value disappears.
This is because the display role changes to "edit", so this fixes that.

Loki-script: double click should not clear cell

---

nicos_ess/loki/gui/loki_scriptbuilder.py

When one selects few empty cells, and paste in the bottom of LoKI Prototype panel table, then unnecessary new rows were created. This PR fixes it.

Handle unnecessary empty cells copy-paste

---

nicos_ess/loki/gui/loki_scriptbuilder.py

This PR enables right click context menu for `copy`, `cut`, `paste` and `delete` actions in the prototype table.

LoKI: Enable right click actions in prototype table

---

nicos/clients/gui/client.py
nicos_ess/gui/panels/setup_panel.py
nicos_ess/loki/gui/setup_exp.py

As title says, the finish button is disabled when pressed. 
Enabled again when the user hits apply changes in the experiment setup.
Fairly simple solution that should adhere to the MV design.

Finish button disabled when pressed and enabled when experiment start

---

nicos_ess/loki/gui/loki_scriptbuilder.py

Allow right click context menu in tableView only and not the entire panel.

Context menu in tableView

---

nicos_ess/loki/gui/measdialogs.py

Let us not use `Black` and `White` to point what is allowed or not in our code base.

Change blacklist to not allowed

---

nicos_ess/utilities/validators.py

This PR implements a validation class. The implementation sweeps all dirty work under the hood and provides a clean API such that the call
`property.setValidator(DoubleValidator(float1, float2, int))`
now is sufficient for proper validation. Here, `float1`, `float2` and `int` represents the minimum, maximum and decimal precision that `property` can assume, respectively. 
The implementation now allows inputs of the form `xx.yy` for floats instead of QT way of `xx,yy`. 
The class inherits from `QDoubleValidator` directly instead of NICOS implementation (`nicos/guisupport/utils.py, line 98`). I believe this is safer in the long run. This can be changed with no effects to implementation (with probably a change in the class name), upon consensus, if necessary.
Remaning issues:
- Numerics of …

Implement Float Validation

---

nicos_ess/loki/gui/experiment_conf.py
nicos_ess/loki/gui/ui_files/exp_config.ui

This PR implements new `DoubleValidator` to Experiment Configuration tab of LoKI GUI, and clears the unnecessary code up.
The sample environment reface positions now read-only as a prep for next iteration of implementation of devices.

LoKI: Implement new validation to experiment configuration

---

nicos_ess/devices/epics/pva/epics_devices.py
nicos_ess/devices/epics/pva/monitor_motor.py

Added capability to set the speed for p4p epics motor device.
@mattclarke I have tested on YMIR. Feel free to take a look yourself.
Branch with local edits (session logging of limits) is still active on ymir server.

ECDC-2551 make motor speed adjustable

---

nicos_ess/devices/experiment.py
nicos_ess/devices/sample.py

This PR tries to fix issue observed while FinishExperiment command is called. In `_update_proposal_info` in setup_panel, the  `Exp.sample.samples`  evaluates to` {0:{'name':''}}`, rather than an empty dictionary.

ECDC:2560 Finish Experiment should clear the samples.

---

nicos_ess/loki/guiconfig.py

This changes the order at the left menu, `Experiment Configuration` now comes before `Samples`.

LoKI: Change menu order

---

nicos_ess/ymir/setups/choppers.py

Renaming chopper devices at YMIR, as suggested in the ticket https://jira.esss.lu.se/browse/ECDC-2589

ECDC-2589: Rename chopper devices at YMIR instrument

---

nicos_ess/ymir/setups/choppers.py

Name changed to match ICS naming convention

Use the new PV name for the chopper delay

---

nicos_ess/ymir/setups/event_receiver.py

Adding nanoseconds.
Tested in simulated case. 
Should be tested in YMIR as well once motion stage tests are completed.

Adding unit to NTP_DIFF in ymir setup
